install:
  - wget https://github.com/unisonweb/unison/releases/download/release%2FM1d/unison-linux64.tar.gz
  - tar -xzvf unison-linux64.tar.gz
script:
  - ./ucm <<< "namespace matrix" <<< "test"
  - ./ucm <<< "namespace matrix" <<< "test" > result.txt
  - grep -q "test(s) failing" result.txt; [ $? -eq 0 ] && exit 1 || exit 0
